### ISSUE TITLE
homebridge-tuya-powerstrip plugin does not load

### ISSUE THREAD

**Issue by blloyd78** [drumfreak/homebridge-tuya-powerstrip#1]
I have installed the plugin via npm and made the necessary changes to the config.json (all settings have been verified working using the homebridge-tuya-outlet plugin previously). But when I reboot my Raspberry Pi to add the new accessories, homebridge fails to start.

The syslog reports problems with a homebridge.hap.Service although I have other plugins using the same service perfectly.

```
Mar 26 23:19:43 TW_Server homebridge[989]: [2018-3-26 23:19:43] Loaded plugin: homebridge-tuya-powerstrip
Mar 26 23:19:43 TW_Server homebridge[989]: /opt/node/lib/node_modules/homebridge-tuya-powerstrip/index.js:6
Mar 26 23:19:43 TW_Server homebridge[989]:   Service = homebridge.hap.Service;
Mar 26 23:19:43 TW_Server homebridge[989]:           ^
Mar 26 23:19:43 TW_Server homebridge[989]: ReferenceError: Service is not defined
Mar 26 23:19:43 TW_Server homebridge[989]:     at Plugin.module.exports [as initializer] (/opt/node/lib/node_modules/homebridge-tu$
Mar 26 23:19:43 TW_Server homebridge[989]:     at Server.<anonymous> (/opt/node/lib/node_modules/homebridge/lib/server.js:160:14)
Mar 26 23:19:43 TW_Server homebridge[989]:     at Array.forEach (native)
Mar 26 23:19:43 TW_Server homebridge[989]:     at Server._loadPlugins (/opt/node/lib/node_modules/homebridge/lib/server.js:138:22)
Mar 26 23:19:43 TW_Server homebridge[989]:     at new Server (/opt/node/lib/node_modules/homebridge/lib/server.js:56:24)
Mar 26 23:19:43 TW_Server homebridge[989]:     at module.exports (/opt/node/lib/node_modules/homebridge/lib/cli.js:26:16)
Mar 26 23:19:43 TW_Server homebridge[989]:     at Object.<anonymous> (/opt/node/lib/node_modules/homebridge/bin/homebridge:17:22)
Mar 26 23:19:43 TW_Server homebridge[989]:     at Module._compile (module.js:569:30)
Mar 26 23:19:43 TW_Server homebridge[989]:     at Object.Module._extensions..js (module.js:580:10)
Mar 26 23:19:43 TW_Server homebridge[989]:     at Module.load (module.js:503:32)
Mar 26 23:19:43 TW_Server homebridge[989]:     at tryModuleLoad (module.js:466:12)
Mar 26 23:19:43 TW_Server homebridge[989]:     at Function.Module._load (module.js:458:3)
Mar 26 23:19:43 TW_Server homebridge[989]:     at Function.Module.runMain (module.js:605:10)
Mar 26 23:19:43 TW_Server homebridge[989]:     at startup (bootstrap_node.js:158:16)
Mar 26 23:19:43 TW_Server homebridge[989]:     at bootstrap_node.js:575:3
Mar 26 23:19:43 TW_Server systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 26 23:19:43 TW_Server systemd[1]: homebridge.service: Unit entered failed state.
Mar 26 23:19:43 TW_Server systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

**Comment by drumfreak** [comment]
Hi, check out the new update. I believe this should be fixed!

`npm i -g homebridge-tuya-powerstrip`

Good luck! Please read the Sniffing procedures in the documentation.. it's a party!

**Comment by blloyd78** [comment]
@drumfreak The update now allows one single outlet plug to work, but if you add a second one to the config.json, the plugin fails to load again.

**Comment by drumfreak** [comment]
Are you using separate names? There's something in homebridge about adding things with unique names.  Also, I highly recommend mapping each tuya device to a static IP on your router, this helps tremendously in load times as it doesn't have to try and resolve the IP through some code I pulled in on this project.  In the future the platform I intend to create should just be able to use your username / password from the tuya app and pull your devices.

Thanks for reporting back!  Please enable debugging in the outlet you're trying to add and post back with any errors. 
 
Last, you could try to clear out your homebridge accessories cache.  

Stop homebridge then: 

`rm ~/.homebridge/accessories/cachedAccessories`

And start it back up.

**Comment by blloyd78** [comment]
I've followed your instructions, but the problem persists. With one Tuya power outlet enabled, everything works for an hour or two, then all accessories stop communicating, generating the "Not Found" error. Add a second power outlet and Homebridge never fully loads. Remove all reference to TiyaPowerStrip from config.json however, and all other accessories (Bose Speaker, Milight bulbs) start working again.

Here's the relevant snippet from my config.json:

```
{
        				"accessory": "TuyaPowerStrip",
        				"name": "Animal Lights",
       					"description" : "Animals Power Outlet",
        				"ip": "192.168.1.166",
        				"devId": "02200397b4e62d066cda",
        				"localKey": "07bf0580739a660b",
        				"dps" : 1,
        				"apiMinTimeout" : 100,
        				"apiMaxTimeout" : 1000,
        				"apiRetries": 1,
        				"apiDebug" : false,
        				"refreshInterval" : 120,
        				"debugPrefix" : "~~~!~~~ ",
       					"debug" : false,
        				"deviceEnabled" : true
    					},
    					{
        				"accessory": "TuyaPowerStrip",
        				"name": "Craft Room Plug",
        				"description" : "Craft Room Power Outlet",
        				"ip": "192.168.1.57",
        				"devId": "0120090468c63aa2d095",
        				"localKey": "e20b8ce991ab50b9",
        				"dps" : 1,
        				"apiMinTimeout" : 100,
        				"apiMaxTimeout" : 1000,
        				"apiRetries": 1,
        				"apiDebug" : false,
        				"refreshInterval" : 120,
        				"debugPrefix" : "~~~!~~~ ",
        				"debug" : false,
        				"deviceEnabled" : true
    					}
```
Everything looks ok, and passes the jsonlint test.

**Comment by drumfreak** [comment]
Did you by chance update the homebridge-tuya-powerstrip plugin when you updated the api!

**Comment by blloyd78** [comment]
Having spent many hours on this issue, it appears to be down to the plug itself. Although clearly Tuya compatible, there is something not quite right as I have another Tuya outlet that seems to work fine.

Very strange
